const REGION_KEY_VALUE = {
    A: '北京',
    B: '天津',
    C1: '石家庄',
    C2: '唐山',
    C3: '廊坊',
    C4: '保定',
    C5: '沧州',
    C6: '衡水',
    C7: '邢台',
    C8: '邯郸',
    D1: '太原',
    D2: '阳泉',
    D3: '长治',
    D4: '晋城',
    E1: '济南',
    E2: '淄博',
    E3: '济宁',
    E4: '德州',
    E5: '聊城',
    E6: '滨州',
    E7: '菏泽',
    F1: '郑州',
    F2: '开封',
    F3: '安阳',
    F4: '鹤壁',
    F5: '新乡',
    F6: '焦作',
    F7: '濮阳',
}
export const RSM_REGION_KEY_VALUE = {
    "1": "北京",
    "2": "天津",
    "3": "石家庄",
    "4": "唐山",
    "5": "秦皇岛",
    "6": "邯郸",
    "7": "邢台",
    "8": "保定",
    "9": "张家口",
    "10": "承德",
    "11": "沧州",
    "12": "廊坊",
    "13": "衡水",
    "14": "太原",
    "15": "大同",
    "16": "阳泉",
    "17": "长治",
    "18": "晋城",
    "19": "朔州",
    "20": "晋中",
    "21": "运城",
    "22": "忻州",
    "23": "临汾",
    "24": "吕梁",
    "25": "济南",
    "26": "青岛",
    "27": "淄博",
    "28": "枣庄",
    "29": "东营",
    "30": "烟台",
    "31": "潍坊",
    "32": "济宁",
    "33": "泰安",
    "34": "威海",
    "35": "日照",
    "36": "临沂",
    "37": "德州",
    "38": "聊城",
    "39": "滨州",
    "40": "菏泽",
    "41": "郑州",
    "42": "开封",
    "43": "洛阳",
    "44": "平顶山",
    "45": "安阳",
    "46": "鹤壁",
    "47": "新乡",
    "48": "焦作",
    "49": "濮阳",
    "50": "许昌",
    "51": "漯河",
    "52": "三门峡",
    "53": "南阳",
    "54": "商丘",
    "55": "信阳",
    "56": "周口",
    "57": "驻马店",
    "58": "济源"
};
export const RSM_REGION = [
    { "label": "北京", "value": "beijing", "children": [{ "label": "北京", "value": "1" }] },
    { "label": "天津", "value": "tianjin", "children": [{ "label": "天津", "value": "2" }] },
    {
        "label": "河北",
        "value": "hebei",
        "children": [
            { "label": "石家庄", "value": "3" },
            { "label": "唐山", "value": "4" },
            { "label": "秦皇岛", "value": "5" },
            { "label": "邯郸", "value": "6" },
            { "label": "邢台", "value": "7" },
            { "label": "保定", "value": "8" },
            { "label": "张家口", "value": "9" },
            { "label": "承德", "value": "10" },
            { "label": "沧州", "value": "11" },
            { "label": "廊坊", "value": "12" },
            { "label": "衡水", "value": "13" }
        ]
    },
    {
        "label": "山西",
        "value": "shanxi",
        "children": [
            { "label": "太原", "value": "14" },
            { "label": "大同", "value": "15" },
            { "label": "阳泉", "value": "16" },
            { "label": "长治", "value": "17" },
            { "label": "晋城", "value": "18" },
            { "label": "朔州", "value": "19" },
            { "label": "晋中", "value": "20" },
            { "label": "运城", "value": "21" },
            { "label": "忻州", "value": "22" },
            { "label": "临汾", "value": "23" },
            { "label": "吕梁", "value": "24" }
        ]
    },
    {
        "label": "山东",
        "value": "shandong",
        "children": [
            { "label": "济南", "value": "25" },
            { "label": "青岛", "value": "26" },
            { "label": "淄博", "value": "27" },
            { "label": "枣庄", "value": "28" },
            { "label": "东营", "value": "29" },
            { "label": "烟台", "value": "30" },
            { "label": "潍坊", "value": "31" },
            { "label": "济宁", "value": "32" },
            { "label": "泰安", "value": "33" },
            { "label": "威海", "value": "34" },
            { "label": "日照", "value": "35" },
            { "label": "临沂", "value": "36" },
            { "label": "德州", "value": "37" },
            { "label": "聊城", "value": "38" },
            { "label": "滨州", "value": "39" },
            { "label": "菏泽", "value": "40" }
        ]
    },
    {
        "label": "河南",
        "value": "henan",
        "children": [
            { "label": "郑州", "value": "41" },
            { "label": "开封", "value": "42" },
            { "label": "洛阳", "value": "43" },
            { "label": "平顶山", "value": "44" },
            { "label": "安阳", "value": "45" },
            { "label": "鹤壁", "value": "46" },
            { "label": "新乡", "value": "47" },
            { "label": "焦作", "value": "48" },
            { "label": "濮阳", "value": "49" },
            { "label": "许昌", "value": "50" },
            { "label": "漯河", "value": "51" },
            { "label": "三门峡", "value": "52" },
            { "label": "南阳", "value": "53" },
            { "label": "商丘", "value": "54" },
            { "label": "信阳", "value": "55" },
            { "label": "周口", "value": "56" },
            { "label": "驻马店", "value": "57" },
            { "label": "济源", "value": "58" }
        ]
    }
];
export default REGION_KEY_VALUE;